// <auto-generated />
using System;
using CanteenManage.CanteenRepository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CanteenManage.Migrations
{
    [DbContext(typeof(CanteenManageDBContext))]
    [Migration("20250504104254_canteenDBMig1")]
    partial class canteenDBMig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CanteenManage.Repo.Models.EmployType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "CanteenStaf",
                            Name = "CanteenStaf"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Employee",
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployTypeId");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            EmployID = "EMP001",
                            EmployTypeId = 3,
                            IsActive = true,
                            Name = "Ardhendu Sekhar Sahoo",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            EmployID = "EMP002",
                            EmployTypeId = 3,
                            IsActive = true,
                            Name = "Rojalin ",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 3,
                            Email = "",
                            EmployID = "EMP003",
                            EmployTypeId = 2,
                            IsActive = true,
                            Name = "Satyajit",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 4,
                            Email = "",
                            EmployID = "EMP004",
                            EmployTypeId = 1,
                            IsActive = true,
                            Name = "Ardhendu Admin",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            FoodTypeId = 1,
                            ImageUrl = "Veg_Sandwich.jpg",
                            IsAvailable = true,
                            Name = "Veg Sandwich",
                            Price = 60m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dosa with Sambar & Chutney",
                            FoodTypeId = 1,
                            ImageUrl = "Masala_Dosa.jpg",
                            IsAvailable = true,
                            Name = "Masala Dosa",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Paratha with Curd & Pickle",
                            FoodTypeId = 1,
                            ImageUrl = "Paratha.jpg",
                            IsAvailable = true,
                            Name = "Paratha",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Poha with Sev & Lemon",
                            FoodTypeId = 1,
                            ImageUrl = "Poha.jpg",
                            IsAvailable = true,
                            Name = "Poha",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Idli (4 pcs) with Sambar & Chutney",
                            FoodTypeId = 1,
                            ImageUrl = "Idli.jpg",
                            IsAvailable = true,
                            Name = "Idli",
                            Price = 40m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Aloo Puri (4 puris)",
                            FoodTypeId = 1,
                            ImageUrl = "Aloo Puri.jpg",
                            IsAvailable = true,
                            Name = "Aloo Puri",
                            Price = 40m
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            FoodTypeId = 1,
                            ImageUrl = "Bread_Omelette.jpg",
                            IsAvailable = true,
                            Name = "Bread & Omelette",
                            Price = 40m
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            FoodTypeId = 1,
                            ImageUrl = "Chai_Tea.jpg",
                            IsAvailable = true,
                            Name = "Chai (Tea)",
                            Price = 15m
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Veg_Thali.jpg",
                            IsAvailable = true,
                            Name = "Veg Thali",
                            Price = 120m
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Chole_Chawal.jpg",
                            IsAvailable = true,
                            Name = "Chole Chawal",
                            Price = 140m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Veg Biryani with Raita",
                            FoodTypeId = 2,
                            ImageUrl = "Veg_Biryani.jpg",
                            IsAvailable = true,
                            Name = "Veg Biryani",
                            Price = 110m
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Rajma_Chawal.jpg",
                            IsAvailable = true,
                            Name = "Rajma Chawal",
                            Price = 90m
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Chicken_Thali.jpg",
                            IsAvailable = true,
                            Name = "Chicken Thali",
                            Price = 160m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Egg Curry with Rice or 2 Rotis",
                            FoodTypeId = 2,
                            ImageUrl = "Chicken_Thali.jpg",
                            IsAvailable = true,
                            Name = "Egg Curry with Rice",
                            Price = 100m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Chicken Biryani with Raita",
                            FoodTypeId = 2,
                            ImageUrl = "Chicken_Biryani.jpg",
                            IsAvailable = true,
                            Name = "Chicken Biryani",
                            Price = 150m
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Fish_Curry_Rice.jpg",
                            IsAvailable = true,
                            Name = "Fish Curry with Rice",
                            Price = 170m
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Roti.jpg",
                            IsAvailable = true,
                            Name = "Roti",
                            Price = 10m
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Curd.jpg",
                            IsAvailable = true,
                            Name = "Curd",
                            Price = 20m
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            FoodTypeId = 2,
                            ImageUrl = "Salad.jpg",
                            IsAvailable = true,
                            Name = "Salad",
                            Price = 15m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Papad (Roasted/Fried)",
                            FoodTypeId = 2,
                            ImageUrl = "Papad.jpg",
                            IsAvailable = true,
                            Name = "Papad",
                            Price = 10m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Samosa (2 pcs)",
                            FoodTypeId = 3,
                            ImageUrl = "Samosa.jpg",
                            IsAvailable = true,
                            Name = "Samosa",
                            Price = 30m
                        },
                        new
                        {
                            Id = 22,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Veg_Puff.jpg",
                            IsAvailable = true,
                            Name = "Veg Puff",
                            Price = 25m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Bread Pakora (2 pcs)",
                            FoodTypeId = 3,
                            ImageUrl = "Bread_Pakora.jpg",
                            IsAvailable = true,
                            Name = "Bread Pakora",
                            Price = 40m
                        },
                        new
                        {
                            Id = 24,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Onion_Pakoda.jpg",
                            IsAvailable = true,
                            Name = "Onion Pakoda",
                            Price = 45m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Aloo Tikki (2 pcs)",
                            FoodTypeId = 3,
                            ImageUrl = "Aloo_Tikki.jpg",
                            IsAvailable = true,
                            Name = "Aloo Tikki",
                            Price = 40m
                        },
                        new
                        {
                            Id = 26,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Maggi_Noodles.jpg",
                            IsAvailable = true,
                            Name = "Maggi Noodles",
                            Price = 30m
                        },
                        new
                        {
                            Id = 27,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Pav_Bhaji.jpg",
                            IsAvailable = true,
                            Name = "Pav Bhaji",
                            Price = 70m
                        },
                        new
                        {
                            Id = 28,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Roll_Veg.jpg",
                            IsAvailable = true,
                            Name = "Roll (Veg)",
                            Price = 40m
                        },
                        new
                        {
                            Id = 29,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Non_Veg_Roll.jpg",
                            IsAvailable = true,
                            Name = "Non-Veg Roll",
                            Price = 50m
                        },
                        new
                        {
                            Id = 30,
                            Description = "",
                            FoodTypeId = 3,
                            ImageUrl = "Chai.jpg",
                            IsAvailable = true,
                            Name = "Chai (Tea)",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodOrders");
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evening Snacks"
                        });
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.Employe", b =>
                {
                    b.HasOne("CanteenManage.Repo.Models.EmployType", "EmployType")
                        .WithMany("Employes")
                        .HasForeignKey("EmployTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployType");
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.Food", b =>
                {
                    b.HasOne("CanteenManage.Repo.Models.FoodType", "FoodType")
                        .WithMany("Foods")
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodType");
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.FoodOrder", b =>
                {
                    b.HasOne("CanteenManage.Repo.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanteenManage.Repo.Models.Food", "Food")
                        .WithMany("FoodOrders")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.EmployType", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.Food", b =>
                {
                    b.Navigation("FoodOrders");
                });

            modelBuilder.Entity("CanteenManage.Repo.Models.FoodType", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
